---
version: '3.8'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  nginx:
    image: shubhamtatvamasi/nginx-file-explorer
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./downloads:/home/:ro
    restart: unless-stopped

  ftp:
    image: metabrainz/docker-anon-ftp
    container_name: ftp
    ports:
      - "20-21:20-21"
      - "65500-65515:65500-65515"
    volumes:
      - ./downloads:/var/ftp:ro
    environment:
      - PASV_ADDRESS=192.168.1.212
    restart: unless-stopped
